### PR TITLE
Lora-gateway-os frequency update

### PR DESCRIPTION
**Pull request by tonysmith55**

### CODE REVIEW

**Comment by tonysmith55** [comment]
February updates

**Comment by brocaar** [comment]
Hi @tonysmith55 , thanks for the February updates ;-) Please note that I made some changes since your previous pull-request. Could you make your filenames match the following pattern?
image

That will make it easier to see the actual diff between the old and new files.

**Comment by brocaar** [comment]
I've been doing all the renaming and the only significant change is in `au915_0.json`:

image

I don't think this is correct. According the Regional Parameters, channel 4 (which is using radio 1) is using 916Mhz. The current `freq` is 916.3 Mhz. For channel 4, the `if` is -300000 (-0.3 Mhz), which maps to 916 Mhz in the current configuration.

The other changes are related to the `gatewayID`, which I don't think are relevant because the `gatewayID` is overwritten.


Please let me know if I made a mistake somewhere. Please create the next PR based on the latest `master` version, that saves me the trouble of renaming all the files ;-)

**Comment by tonysmith55** [comment]
Hi Brocaar,  Sorry about the mistake.   You are correct, Radio 1 should be on 916.3Mhz and with Channel 4 having an IF of -0.3Mhz resulting in 916Mhz.
The more recent frequency proposals at https://github.com/tonysmith55/lora-gateway-additions should be in the correct format.  Had trouble with GitHub (still a novice) so dropped the files in a new repo.

**Pull request closed without merging**
