### PR TITLE
some pre-configure for rak831 easy use

### PR DESCRIPTION
**Pull request by RAKWireless**
1.adjust gateway-config menu for rak831
2.load pre-configured postgresql data for easy of use.

### CODE REVIEW

**Comment by tonysmith55** [comment]
@RAKWireless, I see you have submitted just one configuration for Australia and only one for US.  The current proposal is to create configurations for all possible channel and not be limited to following the channels selected by TTN.
Can you confirm the configuration files for RAK831 will also apply to RAK833 and RAK2245?

**Comment by brocaar** [comment]
Thanks @RAKWireless ! A couple of comments:

* It seems that this pull-request makes the `gateway-config` RAK831 specific and removes the other shield options.
* It also removes the AU and US channel-blocks that @tonysmith55 implemented a couple of days ago.

I'm looking forward to integrate the extra channel configuration and database setup, altough I think it is better to not extract a `.tar.gz` data snapshot as this causes issues in case of new PostgreSQL versions as there will be a version mismatch between the data directory and psql binaries. I think it is better include the db setup and queries in the firstboot script. 

What I can do: cherry-pick the extra channel configuration which currently does not exist + the extra database setup (adding the gateway to the organization), @RAKWireless  is that OK with you or would you like to update the pull-request?  @tonysmith55 then later we can extend this configuration with additional channel-blocks where available / needed.

**Comment by RAKWireless** [comment]
Thanks for your comments! @tonysmith55 @brocaar 
Actually, we've made this code based on an old version of LoRa gateway OS. So there is no AU and US channel-blocks which contributed by @tonysmith55 , not removed :)
We'll continue to develop a new version based on the latest version of LoRa gateway OS, and contribute it to this project by updating the pull-request ASAP.

BTW, this code can run on RAK831 and RAK2245 successfully, but not RAK833 now. We'll add some code to support RAK833 in the next version too.

**Comment by tonysmith55** [comment]
@brocaar, I agree,   "cherry-pick the extra channel configuration which currently does not exist" and I will continue to review the LoraWan spec to check for opportunities to create extra channel blocks like produced for US and AU.  
@RAKWireless, out of interest, what types of changes are needed to make an 833 work?

**Comment by brocaar** [comment]
I'm closing this pull-request as this pull-request is outdated and RAK831 support has already been added :)

**Pull request closed without merging**
